### ISSUE TITLE
Crash caused by using shield bash while rf shield is in mainhand. (Redstone Arsenal)

### ISSUE THREAD

**Issue by Akitori** [coolAlias/DynamicSwordSkills#7]
[crash-2017-12-16_20.39.01-server.txt](https://github.com/coolAlias/DynamicSwordSkills/files/1565242/crash-2017-12-16_20.39.01-server.txt)
Yeah this is a big one, sorry about that.

**Comment by coolAlias** [comment]
This portion of the crash dump is interesting:
```
"Netty Epoll Server IO #2" Id=38 BLOCKED on java.util.ArrayDeque@8d7669b owned by "Server thread" Id=17
	at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1371)
	-  blocked on java.util.ArrayDeque@8d7669b
	at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1393)
	at net.minecraft.world.WorldServer.func_152344_a(WorldServer.java:1334)
	at net.minecraft.network.PacketThreadUtil.func_180031_a(SourceFile:10)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:452)
	at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126)
	at net.minecraft.network.play.client.CPacketPlayer$PositionRotation.func_148833_a(SourceFile:18)
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:147)
```
So there seems to be a conflict with the player motion from Dash vs. perhaps some motion and/or rotation set by the other mod upon impact.

Whatever they are doing here is the source of the issue:
```
at cofh.redstonearsenal.item.tool.ItemShieldRF.damageShield(ItemShieldRF.java:115)
```
Do you know if they have their code online?

**Comment by Akitori** [comment]
its right here i believe Cool.

https://github.com/CoFH/RedstoneArsenal

**Comment by coolAlias** [comment]
Thanks. Looks like it's caused by the Dash code continuing to update the client-side motion while the server says "no, actually." Lol.

I'll figure something out.

**Comment by coolAlias** [comment]
This doesn't seem to be applicable anymore - RedstoneArsenal code has updated and the original class no longer exists.
